spring:
  application:
    name: springboot-redis-cluster-demo
  redis:
    cluster:
      nodes:
        - 192.168.5.111:7001
        - 192.168.5.111:7002
        - 192.168.5.111:7003
        - 192.168.5.111:7004
        - 192.168.5.111:7005
        - 192.168.5.111:7006
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制），默认：8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制），默认：8
        max-idle: 8 # 连接池最大空闲连接，默认：8
        min-idle: 0 # 连接池最小空闲连接，默认：0
    timeout: 10000 # 连接超时时间（毫秒）
server:
  port: 9999
